---
driver:
  name: docker
  hostname: apache.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: apache
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - apache
  pillars:
    top.sls:
      base:
        "*":
          - apache

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: apache_server_<%=ENV['PHP_VERSION'] || 'php7'%>
    provisioner:
      pillars-from-files:
        apache.sls: tests/pillar/apache_server_<%=ENV['PHP_VERSION'] || 'php7'%>.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
